In [1]:
import sys
import os
import importlib
import numpy as np

sys.path.append(os.path.abspath(".."))

import gex_predictor.GEx_Predictor

importlib.reload(sys.modules['gex_predictor.GEx_Predictor'])
importlib.reload(sys.modules['gex_predictor'])

from gex_predictor import GEx_Predictor

2026-04-12 13:18:40.361866: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-04-12 13:18:40.384971: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-04-12 13:18:40.384996: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-04-12 13:18:40.385878: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-04-12 13:18:40.390575: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-04-12 13:18:41.565685: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/aloy/home/ddalton/miniconda3/envs/gex_predictor/lib/python3.10/site-packages/tensorflow_hub/__init__.py:61: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

In [2]:
smiles_kaggle_loaded = np.load("smiles_kaggle_testing.npy", allow_pickle=True)

# Example smiles to predict
smiles_kaggle_loaded

array(['CN(C)C/C=C/C(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1O[C@H]1CCOC1',
       'Cc1ccc(NC(=O)c2ccc(CN3CC[C@H](N(C)C)C3)c(C(F)(F)F)c2)cc1Nc1nccc(-c2cncnc2)n1',
       'COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1NC(=O)/C=C/CN1CCCCC1.O',
       'C#Cc1cccc(Nc2ncnc3cc4c(cc23)OCCOCCOCCO4)c1',
       'O=C(c1ccc(/C=C/c2n[nH]c3ccccc23)cc1)N1CCNCC1',
       'COCCNCc1ccc(-c2cc3nccc(Oc4ccc(NC(=S)NC(=O)Cc5ccc(F)cc5)cc4F)c3s2)nc1',
       'CCOc1cc2ncc(C#N)c(Nc3ccc(OCc4ccccn4)c(Cl)c3)c2cc1NC(=O)/C=C/CN(C)C',
       'CCN(CC)CCNC(=O)c1c(C)[nH]c(/C=C2\\C(=O)Nc3ccc(F)cc32)c1C',
       'O=C(/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1)NO',
       'COc1cc2c(cc1OC(C)C)[C@H](c1ccc(Cl)cc1)N(c1ccc(N(C)C[C@H]3CC[C@H](N4CCN(C)C(=O)C4)CC3)cc1)C(=O)C2',
       'O=C(/C=C/c1cccnc1)NCCCCC1CCN(C(=O)c2ccccc2)CC1',
       'Cn1c2ccccc2c2c3c(c4c5ccccc5n(CCC#N)c4c21)CNC3=O',
       'COc1ccc(S(=O)(=O)N(C(C)=O)c2ccccc2/C=C/c2cc[n+]([O-])cc2)cc1',
       'Nc1ncnc2c1c(I)cn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O',
       'C/C(=C\\c1csc(C)n1)[C@@H]1C[C@@H]2O[C@]2(C)CCC[C@H](C)[C@H](O)[C@@H](C)C(=O)C(C)(C)[C@@H](O)CC(=O)N1',
       'FC(F)(F)c1ccc(/C=C/c2nc(COc3ccc(CCCCn4ccnn4)cc3)co2)cc1',
       'COC[C@H](NC(=O)c1cnc(C)s1)C(=O)N[C@@H](COC)C(=O)N[C@@H](Cc1ccccc1)C(=O)[C@@]1(C)CO1',
       'O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1',
       'C[C@]12C=CC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C@@]2(C)[C@H]1CC[C@]2(O)C(=O)CO',
       'C[C@@H]1O[C@@H](O[C@@H]2C=C3CC[C@@H]4[C@H](CC[C@]5(C)[C@@H](c6ccc(=O)oc6)CC[C@]45O)[C@@]3(C)CC2)[C@H](O)[C@H](O)[C@H]1O',
       'CCOc1cc(C(C)(C)C)ccc1C1=N[C@@](C)(c2ccc(Cl)cc2)[C@@](C)(c2ccc(Cl)cc2)N1C(=O)N1CCN(CCCS(C)(=O)=O)CC1',
       'CN1CCN(c2ccc(Nc3cc(-c4cccc(-n5ccc6cc(C7CC7)cc(F)c6c5=O)c4CO)cn(C)c3=O)nc2)CC1',
       'CN(C)Cc1ccc(S(=O)(=O)n2ccc(/C=C/C(=O)NO)c2)cc1',
       'CC1=NN(c2ccc(C(=O)O)cc2)C(=O)/C1=C/c1ccc(-c2cc(C)c(C)cc2[N+](=O)[O-])o1',
       'C=C1/C(=C\\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)CC[C@@H](O)C(C)C)CC[C@@H]23)C[C@@H](O)C[C@@H]1O'],
      dtype=object)

In [3]:
# Using the best fold to predict:
gex_predictor_best_fold = GEx_Predictor(all_folds=False)

[INFO] Using device: cpu
[INFO] Loading fold 4 from /aloy/home/ddalton/git_clones/GEx_Predictor/model/fold_4.pt ...
[INFO] 1 model(s) loaded (best fold only).

In [4]:
predictions = gex_predictor_best_fold.predict(smiles_kaggle_loaded)

[INFO] Starting prediction — input_type=SMILES
ensemble=best fold

[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: CN(C)C/C=C/C(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1O[C@H]1CCOC1
[13:18:43] New largest fragment: CN(C)C/C=C/C(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1O[C@H]1CCOC1 (59)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: Cc1ccc(NC(=O)c2ccc(CN3CC[C@H](N(C)C)C3)c(C(F)(F)F)c2)cc1Nc1nccc(-c2cncnc2)n1
[13:18:43] New largest fragment: Cc1ccc(NC(=O)c2ccc(CN3CC[C@H](N(C)C)C3)c(C(F)(F)F)c2)cc1Nc1nccc(-c2cncnc2)n1 (73)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1NC(=O)/C=C/CN1CCCCC1
[13:18:43] New largest fragment: COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1NC(=O)/C=C/CN1CCCCC1 (58)
[13:18:43] Fragment: O
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: C#Cc1cccc(Nc2ncnc3cc4c(cc23)OCCOCCOCCO4)c1
[13:18:43] New largest fragment: C#Cc1cccc(Nc2ncnc3cc4c(cc23)OCCOCCOCCO4)c1 (50)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: O=C(c1ccc(/C=C/c2n[nH]c3ccccc23)cc1)N1CCNCC1
[13:18:43] New largest fragment: O=C(c1ccc(/C=C/c2n[nH]c3ccccc23)cc1)N1CCNCC1 (45)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: COCCNCc1ccc(-c2cc3nccc(Oc4ccc(NC(=S)NC(=O)Cc5ccc(F)cc5)cc4F)c3s2)nc1
[13:18:43] New largest fragment: COCCNCc1ccc(-c2cc3nccc(Oc4ccc(NC(=S)NC(=O)Cc5ccc(F)cc5)cc4F)c3s2)nc1 (70)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: CCOc1cc2ncc(C#N)c(Nc3ccc(OCc4ccccn4)c(Cl)c3)c2cc1NC(=O)/C=C/CN(C)C
[13:18:43] New largest fragment: CCOc1cc2ncc(C#N)c(Nc3ccc(OCc4ccccn4)c(Cl)c3)c2cc1NC(=O)/C=C/CN(C)C (69)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: CCN(CC)CCNC(=O)c1c(C)[nH]c(/C=C2\C(=O)Nc3ccc(F)cc32)c1C
[13:18:43] New largest fragment: CCN(CC)CCNC(=O)c1c(C)[nH]c(/C=C2\C(=O)Nc3ccc(F)cc32)c1C (56)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: O=C(/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1)NO
[13:18:43] New largest fragment: O=C(/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1)NO (36)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: COc1cc2c(cc1OC(C)C)[C@H](c1ccc(Cl)cc1)N(c1ccc(N(C)C[C@H]3CC[C@H](N4CCN(C)C(=O)C4)CC3)cc1)C(=O)C2
[13:18:43] New largest fragment: COc1cc2c(cc1OC(C)C)[C@H](c1ccc(Cl)cc1)N(c1ccc(N(C)C[C@H]3CC[C@H](N4CCN(C)C(=O)C4)CC3)cc1)C(=O)C2 (94)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: O=C(/C=C/c1cccnc1)NCCCCC1CCN(C(=O)c2ccccc2)CC1
[13:18:43] New largest fragment: O=C(/C=C/c1cccnc1)NCCCCC1CCN(C(=O)c2ccccc2)CC1 (58)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: Cn1c2ccccc2c2c3c(c4c5ccccc5n(CCC#N)c4c21)CNC3=O
[13:18:43] New largest fragment: Cn1c2ccccc2c2c3c(c4c5ccccc5n(CCC#N)c4c21)CNC3=O (47)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: COc1ccc(S(=O)(=O)N(C(C)=O)c2ccccc2/C=C/c2cc[n+]([O-])cc2)cc1
[13:18:43] New largest fragment: COc1ccc(S(=O)(=O)N(C(C)=O)c2ccccc2/C=C/c2cc[n+]([O-])cc2)cc1 (50)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: Nc1ncnc2c1c(I)cn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O
[13:18:43] New largest fragment: Nc1ncnc2c1c(I)cn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O (33)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: C/C(=C\c1csc(C)n1)[C@@H]1C[C@@H]2O[C@]2(C)CCC[C@H](C)[C@H](O)[C@@H](C)C(=O)C(C)(C)[C@@H](O)CC(=O)N1
[13:18:43] New largest fragment: C/C(=C\c1csc(C)n1)[C@@H]1C[C@@H]2O[C@]2(C)CCC[C@H](C)[C@H](O)[C@@H](C)C(=O)C(C)(C)[C@@H](O)CC(=O)N1 (77)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: FC(F)(F)c1ccc(/C=C/c2nc(COc3ccc(CCCCn4ccnn4)cc3)co2)cc1
[13:18:43] New largest fragment: FC(F)(F)c1ccc(/C=C/c2nc(COc3ccc(CCCCn4ccnn4)cc3)co2)cc1 (57)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: COC[C@H](NC(=O)c1cnc(C)s1)C(=O)N[C@@H](COC)C(=O)N[C@@H](Cc1ccccc1)C(=O)[C@@]1(C)CO1
[13:18:43] New largest fragment: COC[C@H](NC(=O)c1cnc(C)s1)C(=O)N[C@@H](COC)C(=O)N[C@@H](Cc1ccccc1)C(=O)[C@@]1(C)CO1 (69)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1
[13:18:43] New largest fragment: O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1 (55)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: C[C@]12C=CC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C@@]2(C)[C@H]1CC[C@]2(O)C(=O)CO
[13:18:43] New largest fragment: C[C@]12C=CC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C@@]2(C)[C@H]1CC[C@]2(O)C(=O)CO (54)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: C[C@@H]1O[C@@H](O[C@@H]2C=C3CC[C@@H]4[C@H](CC[C@]5(C)[C@@H](c6ccc(=O)oc6)CC[C@]45O)[C@@]3(C)CC2)[C@H](O)[C@H](O)[C@H]1O
[13:18:43] New largest fragment: C[C@@H]1O[C@@H](O[C@@H]2C=C3CC[C@@H]4[C@H](CC[C@]5(C)[C@@H](c6ccc(=O)oc6)CC[C@]45O)[C@@]3(C)CC2)[C@H](O)[C@H](O)[C@H]1O (80)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: CCOc1cc(C(C)(C)C)ccc1C1=N[C@@](C)(c2ccc(Cl)cc2)[C@@](C)(c2ccc(Cl)cc2)N1C(=O)N1CCN(CCCS(C)(=O)=O)CC1
[13:18:43] New largest fragment: CCOc1cc(C(C)(C)C)ccc1C1=N[C@@](C)(c2ccc(Cl)cc2)[C@@](C)(c2ccc(Cl)cc2)N1C(=O)N1CCN(CCCS(C)(=O)=O)CC1 (97)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: CN1CCN(c2ccc(Nc3cc(-c4cccc(-n5ccc6cc(C7CC7)cc(F)c6c5=O)c4CO)cn(C)c3=O)nc2)CC1
[13:18:43] New largest fragment: CN1CCN(c2ccc(Nc3cc(-c4cccc(-n5ccc6cc(C7CC7)cc(F)c6c5=O)c4CO)cn(C)c3=O)nc2)CC1 (80)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: CN(C)Cc1ccc(S(=O)(=O)n2ccc(/C=C/C(=O)NO)c2)cc1
[13:18:43] New largest fragment: CN(C)Cc1ccc(S(=O)(=O)n2ccc(/C=C/C(=O)NO)c2)cc1 (43)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: CC1=NN(c2ccc(C(=O)O)cc2)C(=O)/C1=C/c1ccc(-c2cc(C)c(C)cc2[N+](=O)[O-])o1
[13:18:43] New largest fragment: CC1=NN(c2ccc(C(=O)O)cc2)C(=O)/C1=C/c1ccc(-c2cc(C)c(C)cc2[N+](=O)[O-])o1 (52)
[13:18:43] Running Uncharger
[13:18:43] Initializing MetalDisconnector
[13:18:43] Running MetalDisconnector
[13:18:43] Initializing Normalizer
[13:18:43] Running Normalizer
[13:18:43] Running LargestFragmentChooser
[13:18:43] Fragment: C=C1/C(=C\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)CC[C@@H](O)C(C)C)CC[C@@H]23)C[C@@H](O)C[C@@H]1O
[13:18:43] New largest fragment: C=C1/C(=C\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)CC[C@@H](O)C(C)C)CC[C@@H]23)C[C@@H](O)C[C@@H]1O (74)
[13:18:43] Running Uncharger
2026-04-12 13:18:44.077005: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Parsing SMILES: 25it [00:00, 11964.58it/s]
Generating signatures:   0%|          | 0/1 [00:00<?, ?it/s]

1/1 [==============================] - 0s 242ms/step
1/1 [==============================] - 0s 188ms/step

Generating signatures: 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]

[STEP] Converting signatures to tensor and performing prediction...
[INFO] Prediction completed successfully.

In [5]:
predictions

array([[ 2.2639048 ,  0.52193433,  1.0985852 , ..., -0.5226515 ,
         0.84502697, -0.1906185 ],
       [ 1.3785602 ,  0.2921011 ,  0.7082047 , ..., -0.43396783,
         0.19156364, -0.51224566],
       [ 2.280591  ,  0.4950288 ,  1.0020744 , ..., -0.47705403,
         0.73404104, -0.18701164],
       ...,
       [ 0.36036098,  1.710755  ,  0.8923986 , ..., -0.61906517,
         0.68787825,  0.17534932],
       [ 0.10086839,  0.3026393 ,  0.5599578 , ..., -0.31881887,
         0.67757994,  0.10280199],
       [ 0.47007024, -0.25269958,  0.3577818 , ..., -0.18917044,
        -0.06350008, -0.5253787 ]], dtype=float32)

In [6]:
predictions.shape

(25, 1035)

In [7]:
# Using all the folds to predict:
gex_predictor_all_folds = GEx_Predictor(all_folds=True)

[INFO] Using device: cpu
[INFO] Loading fold 1 from /aloy/home/ddalton/git_clones/GEx_Predictor/model/fold_1.pt ...
[INFO] Loading fold 2 from /aloy/home/ddalton/git_clones/GEx_Predictor/model/fold_2.pt ...
[INFO] Loading fold 3 from /aloy/home/ddalton/git_clones/GEx_Predictor/model/fold_3.pt ...
[INFO] Loading fold 4 from /aloy/home/ddalton/git_clones/GEx_Predictor/model/fold_4.pt ...
[INFO] Loading fold 5 from /aloy/home/ddalton/git_clones/GEx_Predictor/model/fold_5.pt ...
[INFO] 5 model(s) loaded (all 5 folds).

In [8]:
predictions2 = gex_predictor_all_folds.predict(smiles_kaggle_loaded)

[INFO] Starting prediction — input_type=SMILES
ensemble=5 folds

Parsing SMILES: 25it [00:00, 10413.90it/s]
Generating signatures:   0%|          | 0/1 [00:00<?, ?it/s]

1/1 [==============================] - 0s 202ms/step
1/1 [==============================] - 0s 191ms/step

Generating signatures: 100%|██████████| 1/1 [00:00<00:00,  2.26it/s]

[STEP] Converting signatures to tensor and performing prediction...
[INFO] Prediction completed successfully.

In [9]:
predictions2

array([[ 2.2654614 ,  0.508595  ,  1.1507574 , ..., -0.52070796,
         0.8655343 , -0.17996466],
       [ 1.4265026 ,  0.35619962,  0.61947536, ..., -0.44545183,
         0.20149454, -0.43258804],
       [ 2.3159955 ,  0.4967981 ,  1.0242145 , ..., -0.47969994,
         0.74782103, -0.19618742],
       ...,
       [ 0.44894314,  1.7453003 ,  0.8228651 , ..., -0.6157415 ,
         0.7408401 ,  0.20535667],
       [ 0.14932483,  0.18792817,  0.56642294, ..., -0.30796382,
         0.68441963,  0.08223657],
       [ 0.49295244, -0.28999132,  0.35869703, ..., -0.19367322,
        -0.07503041, -0.5003568 ]], dtype=float32)

In [10]:
mae = np.mean(np.abs(predictions - predictions2))
mse = np.mean((predictions - predictions2) ** 2)

print(f"MAE:  {mae:.4f}")
print(f"MSE:  {mse:.4f}")

MAE:  0.0691
MSE:  0.0120

In [12]:
df_predictions = gex_predictor_best_fold.predict(smiles_kaggle_loaded, as_dataframe=True)

[INFO] Starting prediction — input_type=SMILES
ensemble=best fold

Parsing SMILES: 25it [00:00, 10135.09it/s]
Generating signatures:   0%|          | 0/1 [00:00<?, ?it/s]

1/1 [==============================] - 0s 207ms/step
1/1 [==============================] - 0s 181ms/step

Generating signatures: 100%|██████████| 1/1 [00:00<00:00,  2.29it/s]

[STEP] Converting signatures to tensor and performing prediction...
[INFO] Prediction completed successfully.

In [11]:
df_predictions2 = gex_predictor_all_folds.predict(smiles_kaggle_loaded, as_dataframe=True)

[INFO] Starting prediction — input_type=SMILES
ensemble=5 folds

Parsing SMILES: 25it [00:00, 8746.88it/s]
Generating signatures:   0%|          | 0/1 [00:00<?, ?it/s]

WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7e356f52b9a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7e356f52b9a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 [==============================] - 0s 206ms/step
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7e356f52bd00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7e356f52bd00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 [==============================] - 0s 188ms/step

Generating signatures: 100%|██████████| 1/1 [00:00<00:00,  2.21it/s]

[STEP] Converting signatures to tensor and performing prediction...
[INFO] Prediction completed successfully.

In [14]:
df_predictions

,AARS,ABCB6,ABCC5,ABCF1,ABCF3,ABHD4,ABHD6,ABL1,ACAA1,ACAT2,...,ZNF131,ZNF274,ZNF318,ZNF395,ZNF451,ZNF586,ZNF589,ZNHIT3,ZRSR2,ZW10
CN(C)C/C=C/C(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1O[C@H]1CCOC1,2.263905,0.521934,1.098585,0.673512,-0.752429,3.037626,1.906117,-0.086346,-0.687247,0.520542,...,0.481484,-0.030547,0.287575,0.449630,1.099669,0.403577,1.064030,-0.522651,0.845027,-0.190619
Cc1ccc(NC(=O)c2ccc(CN3CC[C@H](N(C)C)C3)c(C(F)(F)F)c2)cc1Nc1nccc(-c2cncnc2)n1,1.378560,0.292101,0.708205,0.571660,-0.532572,1.818971,1.259181,-0.245649,0.185173,2.235568,...,-0.085550,-0.782062,0.588387,0.946480,0.237150,0.044593,0.640985,-0.433968,0.191564,-0.512246
COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1NC(=O)/C=C/CN1CCCCC1.O,2.280591,0.495029,1.002074,0.628881,-0.688685,2.908400,1.723536,-0.103690,-0.606284,0.610154,...,0.405640,-0.128652,0.225690,0.434402,0.978789,0.273073,0.946709,-0.477054,0.734041,-0.187012
C#Cc1cccc(Nc2ncnc3cc4c(cc23)OCCOCCOCCO4)c1,2.845008,0.137591,-0.010716,-0.017537,0.170329,1.080949,0.312457,0.194565,0.072746,-0.947843,...,0.488426,-0.653333,0.040114,0.217300,0.796795,0.078276,0.319080,0.187009,0.436239,-0.195750
O=C(c1ccc(/C=C/c2n[nH]c3ccccc23)cc1)N1CCNCC1,-0.452497,0.175730,0.334066,0.647664,-0.706448,0.637543,1.462471,-0.558390,0.679046,-0.071401,...,0.100122,0.451568,-0.154136,0.674611,-0.107526,0.005247,0.784351,-0.587845,0.233757,-0.537745
COCCNCc1ccc(-c2cc3nccc(Oc4ccc(NC(=S)NC(=O)Cc5ccc(F)cc5)cc4F)c3s2)nc1,0.725887,0.151005,0.236880,-0.025747,-0.135300,0.592483,0.264372,-0.105931,0.248927,0.077384,...,0.141990,-0.170051,0.091038,-0.140226,0.117325,0.044182,0.137997,0.051972,-0.014653,-0.069547
CCOc1cc2ncc(C#N)c(Nc3ccc(OCc4ccccn4)c(Cl)c3)c2cc1NC(=O)/C=C/CN(C)C,3.407502,0.471916,0.932152,0.574387,-0.526006,2.598672,1.352357,0.189516,-0.504018,0.484927,...,0.673936,-0.102598,0.434333,0.393842,1.349267,0.443784,0.895932,-0.312986,1.093151,-0.246575
CCN(CC)CCNC(=O)c1c(C)[nH]c(/C=C2\C(=O)Nc3ccc(F)cc32)c1C,1.065372,0.126571,0.455582,0.989743,-0.640588,2.378504,1.543507,-0.116126,0.324989,2.068407,...,0.083510,-0.567315,0.673343,1.226599,0.854696,0.249067,0.998405,-0.296489,0.669448,-0.521315
O=C(/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1)NO,0.442761,1.125126,0.479225,0.966483,3.514280,0.249428,3.574694,-2.707541,2.052505,-3.025592,...,-0.717534,-1.556300,-0.666114,0.579882,-0.296335,-0.194334,0.819406,-0.324535,0.829123,0.896303
COc1cc2c(cc1OC(C)C)[C@H](c1ccc(Cl)cc1)N(c1ccc(N(C)C[C@H]3CC[C@H](N4CCN(C)C(=O)C4)CC3)cc1)C(=O)C2,0.195026,0.943920,0.440871,0.174219,-0.085400,1.754255,0.616879,-0.435084,0.009101,-0.462708,...,-0.095018,0.155959,-0.106800,0.274404,0.559989,-0.058846,0.399011,-0.051762,0.311755,-0.287512
O=C(/C=C/c1cccnc1)NCCCCC1CCN(C(=O)c2ccccc2)CC1,0.279419,-0.149846,0.306185,-0.012814,-0.087633,0.116368,0.153409,-0.165796,0.146498,-0.443475,...,0.241132,0.053413,0.052045,-0.234051,0.266674,0.047882,0.182657,0.053402,-0.085585,-0.223944
Cn1c2ccccc2c2c3c(c4c5ccccc5n(CCC#N)c4c21)CNC3=O,0.840013,0.208309,0.105384,0.370060,0.070327,0.181795,1.009306,-0.199452,0.589608,-0.640847,...,0.531592,0.235705,-0.307762,-0.068667,0.317624,-0.226271,0.158760,0.106463,0.322332,-0.209011
COc1ccc(S(=O)(=O)N(C(C)=O)c2ccccc2/C=C/c2cc[n+]([O-])cc2)cc1,2.062439,0.151092,0.710549,0.389161,-0.151389,2.496977,0.731947,0.415700,0.087629,0.482402,...,0.374767,0.444722,-0.410654,0.185372,0.588941,0.346036,0.381681,-0.552591,1.065797,-0.254235
Nc1ncnc2c1c(I)cn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O,-1.681140,0.025155,1.738692,0.507219,-3.904043,0.351019,3.360848,-2.888887,0.353973,0.671223,...,-0.801491,1.764679,0.528479,1.602158,0.391893,2.142654,2.939857,-3.625951,-0.039606,-0.850692
C/C(=C\c1csc(C)n1)[C@@H]1C[C@@H]2O[C@]2(C)CCC[C@H](C)[C@H](O)[C@@H](C)C(=O)C(C)(C)[C@@H](O)CC(=O)N1,-0.354786,-1.090462,0.863799,1.052665,-0.680344,-0.223369,1.299705,-0.029921,0.041150,-0.905073,...,-0.964761,-0.177742,0.280364,0.695382,-0.163069,0.342586,0.662774,-0.790661,0.468588,0.167930
FC(F)(F)c1ccc(/C=C/c2nc(COc3ccc(CCCCn4ccnn4)cc3)co2)cc1,1.434141,-0.269050,-0.200500,0.010945,-0.207121,0.235892,0.388875,-0.003330,0.067967,-0.192149,...,0.362864,-0.033662,-0.099042,0.031203,0.388142,-0.040197,-0.011316,0.087491,-0.011397,-0.397156
COC[C@H](NC(=O)c1cnc(C)s1)C(=O)N[C@@H](COC)C(=O)N[C@@H](Cc1ccccc1)C(=O)[C@@]1(C)CO1,0.444829,-1.132911,2.535850,3.330088,1.559371,4.432547,1.622974,0.809175,0.802447,-1.402544,...,0.177549,-0.058421,-0.809386,2.456301,0.573355,1.638154,0.259344,-2.299720,3.469675,0.690135
O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1,-0.193362,0.544628,1.040099,0.466575,-0.207410,1.842924,1.369241,-0.196129,0.620686,0.758210,...,0.045939,0.277891,0.775624,0.887583,0.106186,0.136286,0.770416,-0.526182,0.333422,-0.866800
C[C@]12C=CC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C@@]2(C)[C@H]1CC[C@]2(O)C(=O)CO,-0.099077,-0.051633,0.411456,0.036325,-0.045294,0.173529,0.125361,-0.038540,0.239590,-0.252815,...,0.090354,0.142884,0.213792,0.109302,0.090473,0.169619,0.304948,-0.095507,-0.050096,-0.044855
C[C@@H]1O[C@@H](O[C@@H]2C=C3CC[C@@H]4[C@H](CC[C@]5(C)[C@@H](c6ccc(=O)oc6)CC[C@]45O)[C@@]3(C)CC2)[C@H](O)[C@H](O)[C@H]1O,-3.858343,-2.438304,-0.764263,1.443742,-2.286236,0.084365,0.520444,0.274895,0.158926,-1.283887,...,1.640137,1.818590,-1.415762,0.474654,0.943451,3.908326,0.639122,-0.720139,1.681688,-1.301770
CCOc1cc(C(C)(C)C)ccc1C1=N[C@@](C)(c2ccc(Cl)cc2)[C@@](C)(c2ccc(Cl)cc2)N1C(=O)N1CCN(CCCS(C)(=O)=O)CC1,0.109995,0.779546,0.338159,0.066185,-0.148705,1.297901,0.332538,-0.242764,0.064649,-0.320332,...,0.023331,-0.019288,-0.142149,0.045045,0.435439,-0.095931,0.220316,0.055628,0.193735,-0.160766
CN1CCN(c2ccc(Nc3cc(-c4cccc(-n5ccc6cc(C7CC7)cc(F)c6c5=O)c4CO)cn(C)c3=O)nc2)CC1,0.209284,0.070691,0.263762,-0.206814,0.063962,0.383601,0.175861,0.141913,0.137994,-0.145015,...,0.104896,-0.089876,0.092305,-0.157533,0.007325,0.299244,0.193741,0.044792,-0.067090,-0.158780
CN(C)Cc1ccc(S(=O)(=O)n2ccc(/C=C/C(=O)NO)c2)cc1,0.360361,1.710755,0.892399,0.612356,2.997944,1.455032,4.228055,-3.018786,1.888165,-4.101876,...,-1.475896,-1.273163,-0.636519,0.502836,-0.394424,-0.337854,0.886394,-0.619065,0.687878,0.175349
CC1=NN(c2ccc(C(=O)O)cc2)C(=O)/C1=C/c1ccc(-c2cc(C)c(C)cc2[N+](=O)[O-])o1,0.100868,0.302639,0.559958,0.188381,-0.480942,1.295721,0.297940,0.173596,0.082941,-0.860213,...,0.563778,0.848212,-0.076625,0.241175,0.149297,0.532461,0.267771,-0.318819,0.677580,0.102802
C=C1/C(=C\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)CC[C@@H](O)C(C)C)CC[C@@H]23)C[C@@H](O)C[C@@H]1O,0.470070,-0.252700,0.357782,-0.068951,-0.214879,0.177636,0.031680,0.683577,0.082135,-0.383961,...,0.141267,0.085390,0.106923,0.141096,-0.069453,0.115268,0.337623,-0.189170,-0.063500,-0.525379

In [15]:
df_predictions2

,AARS,ABCB6,ABCC5,ABCF1,ABCF3,ABHD4,ABHD6,ABL1,ACAA1,ACAT2,...,ZNF131,ZNF274,ZNF318,ZNF395,ZNF451,ZNF586,ZNF589,ZNHIT3,ZRSR2,ZW10
CN(C)C/C=C/C(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1O[C@H]1CCOC1,2.265461,0.508595,1.150757,0.683238,-0.766970,3.075150,1.898503,-0.085836,-0.702670,0.508584,...,0.495276,-0.057406,0.264795,0.462950,1.124212,0.375921,1.043437,-0.520708,0.865534,-0.179965
Cc1ccc(NC(=O)c2ccc(CN3CC[C@H](N(C)C)C3)c(C(F)(F)F)c2)cc1Nc1nccc(-c2cncnc2)n1,1.426503,0.356200,0.619475,0.561068,-0.621413,1.818116,1.272580,-0.334895,0.247476,2.179966,...,-0.047547,-0.784366,0.573329,0.907463,0.218460,0.084601,0.677474,-0.445452,0.201495,-0.432588
COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1NC(=O)/C=C/CN1CCCCC1.O,2.315995,0.496798,1.024215,0.619807,-0.723545,2.891510,1.736723,-0.105531,-0.607464,0.609035,...,0.405929,-0.185561,0.237191,0.450199,1.041692,0.267662,0.935518,-0.479700,0.747821,-0.196187
C#Cc1cccc(Nc2ncnc3cc4c(cc23)OCCOCCOCCO4)c1,2.814492,0.183269,-0.024915,-0.014817,0.197795,1.116361,0.386358,0.176312,0.117913,-1.049555,...,0.496147,-0.724383,0.017826,0.230362,0.795405,0.084091,0.318940,0.188896,0.447773,-0.204812
O=C(c1ccc(/C=C/c2n[nH]c3ccccc23)cc1)N1CCNCC1,0.290451,0.106128,0.324860,0.612667,-0.377190,0.619499,1.169200,-0.284771,0.550546,-0.332423,...,0.140262,0.133312,-0.051086,0.483306,0.075711,-0.051158,0.673458,-0.395968,0.267360,-0.442525
COCCNCc1ccc(-c2cc3nccc(Oc4ccc(NC(=S)NC(=O)Cc5ccc(F)cc5)cc4F)c3s2)nc1,0.626008,0.099525,0.264402,0.010603,-0.158722,0.533277,0.292896,-0.082973,0.232542,0.036917,...,0.141595,-0.128603,0.100197,-0.091286,0.093318,0.137484,0.154500,0.006923,0.006081,-0.097261
CCOc1cc2ncc(C#N)c(Nc3ccc(OCc4ccccn4)c(Cl)c3)c2cc1NC(=O)/C=C/CN(C)C,3.366084,0.407741,0.997317,0.620618,-0.525298,2.635167,1.380363,0.190731,-0.538512,0.434273,...,0.677288,-0.212095,0.443589,0.434179,1.345688,0.476001,0.949257,-0.292038,1.070638,-0.328812
CCN(CC)CCNC(=O)c1c(C)[nH]c(/C=C2\C(=O)Nc3ccc(F)cc32)c1C,0.917564,0.041300,0.442801,0.989085,-0.710097,2.139655,1.613157,-0.177558,0.341964,1.762097,...,0.102977,-0.386081,0.651715,1.201746,0.724336,0.138421,1.099759,-0.373273,0.621248,-0.500417
O=C(/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1)NO,0.463566,1.267788,0.587373,0.935929,3.684837,0.312765,3.642375,-2.797456,2.215107,-3.167653,...,-0.728864,-1.507308,-0.658508,0.575594,-0.386055,-0.111250,0.859769,-0.345570,0.851973,0.876785
COc1cc2c(cc1OC(C)C)[C@H](c1ccc(Cl)cc1)N(c1ccc(N(C)C[C@H]3CC[C@H](N4CCN(C)C(=O)C4)CC3)cc1)C(=O)C2,0.410366,0.915734,0.470071,0.127960,-0.097986,1.762218,0.683676,-0.414514,-0.051110,-0.606613,...,-0.079880,0.181303,-0.099166,0.290928,0.603500,-0.001952,0.398386,-0.043652,0.353177,-0.435037
O=C(/C=C/c1cccnc1)NCCCCC1CCN(C(=O)c2ccccc2)CC1,0.223648,-0.098528,0.334463,0.002006,-0.085817,0.180637,0.204488,-0.168109,0.193748,-0.457089,...,0.252880,0.047281,0.044361,-0.270865,0.231837,0.027459,0.207715,0.061194,-0.104743,-0.190068
Cn1c2ccccc2c2c3c(c4c5ccccc5n(CCC#N)c4c21)CNC3=O,0.526262,0.118090,0.126328,0.538001,-0.229616,0.396145,1.191636,-0.331451,0.591724,-0.536824,...,0.309630,0.328944,-0.261428,0.260854,0.197669,-0.089835,0.443015,-0.146105,0.307856,-0.363483
COc1ccc(S(=O)(=O)N(C(C)=O)c2ccccc2/C=C/c2cc[n+]([O-])cc2)cc1,1.236891,0.045888,0.778742,0.406766,-0.018829,2.235457,0.786568,0.331652,0.243061,-0.186237,...,0.329918,0.374849,-0.325110,0.146497,0.474984,0.210495,0.441085,-0.460034,0.972678,-0.231371
Nc1ncnc2c1c(I)cn2[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O,-1.763416,0.041819,1.804121,0.492176,-3.958542,0.295323,3.423592,-2.897473,0.321675,0.718594,...,-0.850577,1.820740,0.650127,1.627241,0.401565,2.259994,3.047184,-3.763189,-0.054572,-0.819253
C/C(=C\c1csc(C)n1)[C@@H]1C[C@@H]2O[C@]2(C)CCC[C@H](C)[C@H](O)[C@@H](C)C(=O)C(C)(C)[C@@H](O)CC(=O)N1,-0.328773,-1.059121,0.782175,0.960656,-0.670598,-0.196523,1.129101,-0.005973,-0.010591,-0.809423,...,-0.774576,-0.143148,0.316283,0.655171,-0.108478,0.383372,0.620191,-0.743041,0.469016,0.174567
FC(F)(F)c1ccc(/C=C/c2nc(COc3ccc(CCCCn4ccnn4)cc3)co2)cc1,0.427426,-0.184008,0.047270,-0.019612,-0.137631,0.201650,0.231822,0.016941,0.143223,-0.156342,...,0.220111,0.043100,0.039743,-0.107570,0.253991,-0.021342,0.036510,0.077296,-0.046219,-0.163338
COC[C@H](NC(=O)c1cnc(C)s1)C(=O)N[C@@H](COC)C(=O)N[C@@H](Cc1ccccc1)C(=O)[C@@]1(C)CO1,0.566646,-1.236789,2.769819,3.443213,1.696469,4.608366,1.379870,0.829805,0.918492,-1.210751,...,0.201821,-0.000166,-0.866268,2.500476,0.612787,1.617788,0.067106,-2.310528,3.589761,0.762481
O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1,0.081966,0.421048,1.098654,0.370836,-0.239881,1.898228,1.167355,-0.145401,0.506758,1.177397,...,-0.041998,-0.047203,0.725007,0.867579,0.310663,0.203022,0.712597,-0.516614,0.384035,-0.824112
C[C@]12C=CC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C@@]2(C)[C@H]1CC[C@]2(O)C(=O)CO,-0.100309,-0.059797,0.420912,0.057174,-0.067388,0.205725,0.155831,-0.033913,0.227556,-0.292944,...,0.094875,0.149405,0.202437,0.120428,0.113200,0.183896,0.302819,-0.115920,-0.041189,-0.056926
C[C@@H]1O[C@@H](O[C@@H]2C=C3CC[C@@H]4[C@H](CC[C@]5(C)[C@@H](c6ccc(=O)oc6)CC[C@]45O)[C@@]3(C)CC2)[C@H](O)[C@H](O)[C@H]1O,-3.951100,-2.379974,-0.571364,1.528121,-2.374537,0.028286,0.485699,0.332503,0.175495,-1.188039,...,1.610063,1.899568,-1.412277,0.458387,1.127223,3.901366,0.599607,-0.785266,1.648859,-1.260553
CCOc1cc(C(C)(C)C)ccc1C1=N[C@@](C)(c2ccc(Cl)cc2)[C@@](C)(c2ccc(Cl)cc2)N1C(=O)N1CCN(CCCS(C)(=O)=O)CC1,0.221155,0.830433,0.336046,0.053775,-0.158941,1.304352,0.341131,-0.229868,0.054736,-0.347607,...,0.038405,-0.019635,-0.145801,0.044483,0.402418,-0.095957,0.205472,0.088041,0.174161,-0.230708
CN1CCN(c2ccc(Nc3cc(-c4cccc(-n5ccc6cc(C7CC7)cc(F)c6c5=O)c4CO)cn(C)c3=O)nc2)CC1,0.227997,0.029976,0.243875,-0.182941,0.071581,0.374391,0.214164,0.099014,0.129354,-0.213783,...,0.073441,-0.106924,0.095224,-0.127266,0.039808,0.322107,0.231481,0.023543,-0.041486,-0.125888
CN(C)Cc1ccc(S(=O)(=O)n2ccc(/C=C/C(=O)NO)c2)cc1,0.448943,1.745300,0.822865,0.561794,2.816602,1.371288,4.013210,-2.850412,1.917407,-3.986636,...,-1.330786,-1.322875,-0.667131,0.490678,-0.309342,-0.397913,0.905642,-0.615741,0.740840,0.205357
CC1=NN(c2ccc(C(=O)O)cc2)C(=O)/C1=C/c1ccc(-c2cc(C)c(C)cc2[N+](=O)[O-])o1,0.149325,0.187928,0.566423,0.160824,-0.511397,1.374917,0.417263,0.149687,0.113624,-0.727618,...,0.565699,0.951250,-0.030435,0.153384,0.240745,0.515161,0.269752,-0.307964,0.684420,0.082237
C=C1/C(=C\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)CC[C@@H](O)C(C)C)CC[C@@H]23)C[C@@H](O)C[C@@H]1O,0.492952,-0.289991,0.358697,-0.080112,-0.219691,0.152187,0.035106,0.665718,0.062949,-0.427325,...,0.154358,0.081089,0.070687,0.133837,-0.088322,0.088112,0.343790,-0.193673,-0.075030,-0.500357